name: Deploy Vite + React

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run build
      - run: git config --global user.name 'github-actions'
      - run: git config --global user.email 'github-actions@github.com'
      - run: |
          git worktree add gh-pages
          rm -rf gh-pages/*
          cp -r dist/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy GitHub Pages"
          git push origin HEAD:gh-pages --force